### ISSUE TITLE
xgx_save() - status argument doesn't seem to work

### ISSUE THREAD

**Issue by baltcir1** [Novartis/xgxr#16]
The following command didn't produce a TEST label on graphs. Also, it would be good to put an example of use of arguments status_x and status_y.

xgx_save(g = p5 + xgx_annotate_filenames(dirs), status_fontsize = 1, status = "TEST",
         width=12, height=8, dirs, filename_main = filename, filetype = "pdf")

**Comment by iamstein** [comment]
Hi Irina, would be good if you added enough code to create the actual plot, even if it's just dummy data.  Then we could easily debug.  But since we don't have "p5" above, I cannot debug the issue you are seeing.  My guess is that setting the font size to 1 makes it so tiny that you can't see it.  Can you try making it 10 or to confirm it can't show up?  Note that the default value is 7.
