### ISSUE TITLE
mean +/- SD ?

### ISSUE THREAD

**Issue by margoal1** [Novartis/xgxr#32]
Received a request to have an option to plot Mean +/- SD instead of Mean & CI. I think Mean +/- SE is already the default for stat_summary, but what about SD?

**Comment by iamstein** [comment]
Mean ± CI = Mean ± SD when it's a 68% confidence interval (instead of 95th).  As we do give the user the option to set the size of the confidence interval they want, this is easily implementable.  I'd suggest directed the user to use this CI option.
https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule
